sudo: true
dist: trusty
cache:
  directories:
  - node
  - node_modules
language: node_js
node_js:
- 6.9
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- npm install
- ng build
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- ng test --watch false

after_script:
  - cat ./coverage/*/lcov.info | ./node_modules/coveralls/bin/coveralls.js
